"""Compat wrapper for the canonical Platinum PDF styles."""

from app.services.pdf.pdf_styles import (
    PLATINUM_ACCENT,
    PLATINUM_ACCENT_2,
    PLATINUM_BORDER,
    PLATINUM_DANGER,
    PLATINUM_DARK_BORDER,
    PLATINUM_LIGHT,
    PLATINUM_MUTED,
    PLATINUM_PRIMARY,
    PLATINUM_SECONDARY,
    PLATINUM_SOFT,
    PLATINUM_SUCCESS,
    PLATINUM_WARNING,
    PLATINUM_WHITE,
    RISK_COLORS,
    STATUS_COLORS,
    get_platinum_styles,
    platinum_styles,
    risk_color,
    status_color,
)

__all__ = [
    "PLATINUM_ACCENT",
    "PLATINUM_ACCENT_2",
    "PLATINUM_BORDER",
    "PLATINUM_DANGER",
    "PLATINUM_DARK_BORDER",
    "PLATINUM_LIGHT",
    "PLATINUM_MUTED",
    "PLATINUM_PRIMARY",
    "PLATINUM_SECONDARY",
    "PLATINUM_SOFT",
    "PLATINUM_SUCCESS",
    "PLATINUM_WARNING",
    "PLATINUM_WHITE",
    "RISK_COLORS",
    "STATUS_COLORS",
    "get_platinum_styles",
    "platinum_styles",
    "risk_color",
    "status_color",
]
