
// ============================================================
// PÁGINA AUDITORÍA SISTEMA PRO - FASE 35.4.1
// ============================================================
import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, Download, Eye, FileDown, Filter, Globe2, RefreshCcw, Route, Search, ShieldCheck, UserRound, X } from 'lucide-react';
import { getAuditoriaExcelUrl, getAuditoriaPdfUrl, obtenerAuditoriaSistema, obtenerDetalleAuditoria } from '../../api/auditoriaSistemaApi';
import '../../styles/auditoria-sistema-pro.css';
import '../../styles/seguridad-compact.css';
const DEFAULT_FILTERS={usuario_id:'',empresa_id:'',metodo:'',ruta:'',ip:'',q:'',fecha_desde:'',fecha_hasta:'',limit:300};
function metodoClass(m){const v=String(m||'GET').toUpperCase(); if(v==='POST')return'post'; if(v==='PUT'||v==='PATCH')return'put'; if(v==='DELETE')return'delete'; if(v==='OPTIONS')return'options'; return'get';}
function formatFecha(v){if(!v)return'Sin fecha'; try{return new Date(v).toLocaleString('es-CO');}catch{return v;}}
export default function AuditoriaSistemaPage(){
 const [filters,setFilters]=useState(DEFAULT_FILTERS); const [data,setData]=useState({kpis:{},eventos:[],metodos:{},rutas_top:[],usuarios_top:[],recomendaciones:[]}); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [detalle,setDetalle]=useState(null); const [detalleLoading,setDetalleLoading]=useState(false);
 const kpis=data?.kpis||{}; const eventos=data?.eventos||[]; const actividadCritica=useMemo(()=>{const total=Number(kpis.total_eventos||0); if(!total)return 0; return Math.min(100,Math.round(((Number(kpis.eventos_delete||0)+Number(kpis.eventos_sin_usuario||0))/total)*100));},[kpis]);
 async function cargar(custom=filters){setLoading(true);setError('');try{setData(await obtenerAuditoriaSistema(custom));}catch(e){console.error(e);setError(e?.response?.data?.detail||e?.message||'No fue posible cargar la auditoría.');}finally{setLoading(false);}}
 useEffect(()=>{cargar(DEFAULT_FILTERS);},[]);
 function updateFilter(n,v){setFilters(p=>({...p,[n]:v}));} function aplicar(e){e.preventDefault();cargar(filters);} function limpiar(){setFilters(DEFAULT_FILTERS);cargar(DEFAULT_FILTERS);} async function abrirDetalle(id){setDetalleLoading(true);setDetalle(null);try{setDetalle(await obtenerDetalleAuditoria(id));}catch(e){setError(e?.response?.data?.detail||'No fue posible abrir el detalle.');}finally{setDetalleLoading(false);}} function exportar(t){window.open(t==='excel'?getAuditoriaExcelUrl(filters):getAuditoriaPdfUrl(filters),'_blank','noopener,noreferrer');}
 return <section className='auditoria-sistema-page'>
  <div className='as-hero'><div><h1>Auditoría del Sistema</h1><p>Consulta actividad, usuarios, rutas, eventos críticos y trazabilidad.</p></div><div className='as-hero-actions'><button title='Exportar PDF' className='as-btn ghost' onClick={()=>exportar('pdf')}><FileDown size={17}/>PDF</button><button title='Exportar Excel' className='as-btn ghost' onClick={()=>exportar('excel')}><Download size={17}/>Excel</button><button title='Actualizar' className='as-btn primary' onClick={()=>cargar()} disabled={loading}><RefreshCcw size={17}/>{loading?'Actualizando...':'Actualizar'}</button></div></div>
  {error&&<div className='as-alert danger'><AlertTriangle size={18}/>{error}</div>}
  <div className='as-kpi-grid'><article className='as-kpi'><Activity size={22}/><span>Total eventos</span><strong>{kpis.total_eventos||0}</strong></article><article className='as-kpi'><UserRound size={22}/><span>Usuarios únicos</span><strong>{kpis.usuarios_unicos||0}</strong></article><article className='as-kpi'><Globe2 size={22}/><span>IPs únicas</span><strong>{kpis.ips_unicas||0}</strong></article><article className='as-kpi'><Route size={22}/><span>Rutas únicas</span><strong>{kpis.rutas_unicas||0}</strong></article><article className='as-kpi danger'><AlertTriangle size={22}/><span>Sin usuario</span><strong>{kpis.eventos_sin_usuario||0}</strong></article><article className='as-kpi quality'><ShieldCheck size={22}/><span>Riesgo actividad</span><strong>{actividadCritica}%</strong></article></div>
  <div className='as-method-grid'>{Object.entries(data?.metodos||{}).map(([m,t])=><div key={m} className={`as-method ${metodoClass(m)}`}><span>{m||'SIN MÉTODO'}</span><strong>{t}</strong></div>)}</div>
  <form className='as-filters' onSubmit={aplicar}>{[['usuario_id','Usuario ID','number'],['empresa_id','Empresa ID','number'],['ruta','Ruta','text'],['ip','IP','text'],['q','Buscar','text'],['fecha_desde','Desde','date'],['fecha_hasta','Hasta','date'],['limit','Límite','number']].map(([n,l,type])=><div className='as-filter' key={n}><label>{l}</label><input type={type} value={filters[n]} onChange={e=>updateFilter(n,e.target.value)} placeholder={l}/></div>)}<div className='as-filter'><label>Método</label><select value={filters.metodo} onChange={e=>updateFilter('metodo',e.target.value)}><option value=''>Todos</option><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option><option>OPTIONS</option></select></div><button className='as-btn primary' type='submit'><Filter size={16}/>Filtrar</button><button className='as-btn ghost' type='button' onClick={limpiar}>Limpiar</button></form>
  <div className='as-recomendaciones'>{(data?.recomendaciones||[]).map((r,i)=><div className='as-alert' key={i}><BarChart3 size={18}/>{r}</div>)}</div>
  <div className='as-panels'><article className='as-panel'><h2>Top rutas</h2><div className='as-mini-list'>{(data?.rutas_top||[]).map(x=><div key={x.ruta}><span>{x.ruta}</span><strong>{x.total}</strong></div>)}</div></article><article className='as-panel'><h2>Top usuarios</h2><div className='as-mini-list'>{(data?.usuarios_top||[]).map(x=><div key={`${x.usuario_id}-${x.usuario}`}><span>{x.usuario}</span><strong>{x.total}</strong></div>)}</div></article></div>
  <div className='as-table-card'><div className='as-table-header'><div><h2>Eventos de auditoría</h2><p>{eventos.length} registros mostrados</p></div><Search size={20}/></div><div className='as-table-wrap'><table className='as-table'><thead><tr><th>ID</th><th>Fecha</th><th>Usuario</th><th>Método</th><th>Ruta</th><th>IP</th><th>Acción</th><th></th></tr></thead><tbody>{eventos.map(item=><tr key={item.id}><td>#{item.id}</td><td>{formatFecha(item.fecha)}</td><td><strong>{item.usuario_nombre||'Sin usuario'}</strong><small>{item.usuario_correo||`ID ${item.usuario_id||'—'}`}</small></td><td><span className={`as-method-badge ${metodoClass(item.metodo)}`}>{item.metodo||'—'}</span></td><td className='as-route-cell'>{item.ruta||'—'}</td><td>{item.ip||'—'}</td><td>{item.accion||'—'}</td><td><button className='as-icon-btn' onClick={()=>abrirDetalle(item.id)}><Eye size={16}/></button></td></tr>)}{!eventos.length&&<tr><td colSpan='8' className='as-empty'>{loading?'Cargando auditoría...':'No hay eventos con los filtros actuales.'}</td></tr>}</tbody></table></div></div>
  {(detalle||detalleLoading)&&<div className='as-modal-backdrop' onClick={()=>setDetalle(null)}><div className='as-modal' onClick={e=>e.stopPropagation()}><div className='as-modal-header'><div><span>Detalle del evento</span><h2>{detalleLoading?'Cargando...':`Auditoría #${detalle?.id}`}</h2></div><button className='as-icon-btn' onClick={()=>setDetalle(null)}><X size={18}/></button></div>{detalle&&<div className='as-detail-grid'>{[['Fecha',formatFecha(detalle.fecha)],['Usuario',detalle.usuario_nombre||'Sin usuario'],['Empresa',detalle.empresa_nombre||'Global / sin empresa'],['Método',detalle.metodo||'—'],['Ruta',detalle.ruta||'—'],['IP',detalle.ip||'—'],['Acción',detalle.accion||'—'],['User Agent',detalle.user_agent||'Sin registro']].map(([a,b])=><div key={a} className={a.length>6?'wide':''}><label>{a}</label><p>{b}</p></div>)}</div>}</div></div>}
 </section>;
}
