"""Catálogo y grupos de roles del ERP SST.

Este módulo evita que cada router defina nombres incompatibles y documenta la
segregación mínima entre administración técnica, gestión SST, participación,
alta dirección y trabajadores.
"""

SUPER_ADMIN = "SUPER_ADMIN"
ADMIN_EMPRESA = "ADMIN_EMPRESA"
ALTA_DIRECCION = "ALTA_DIRECCION"
REPRESENTANTE_LEGAL = "REPRESENTANTE_LEGAL"
COORDINADOR_SST = "COORDINADOR_SST"
RESPONSABLE_SST = "RESPONSABLE_SST"
TECNICO_SST = "TECNICO_SST"
JEFE_AREA = "JEFE_AREA"
COPASST = "COPASST"
VIGIA_SST = "VIGIA_SST"
TALENTO_HUMANO = "TALENTO_HUMANO"
MEDICO_OCUPACIONAL = "MEDICO_OCUPACIONAL"
AUDITOR = "AUDITOR"
EMPLEADO = "EMPLEADO"
TRABAJADOR = "TRABAJADOR"
CONTRATISTA = "CONTRATISTA"
SOLO_LECTURA = "SOLO_LECTURA"


ROLES_SISTEMA = (
    SUPER_ADMIN,
    ADMIN_EMPRESA,
    ALTA_DIRECCION,
    REPRESENTANTE_LEGAL,
    COORDINADOR_SST,
    RESPONSABLE_SST,
    TECNICO_SST,
    JEFE_AREA,
    COPASST,
    VIGIA_SST,
    TALENTO_HUMANO,
    MEDICO_OCUPACIONAL,
    AUDITOR,
    EMPLEADO,
    TRABAJADOR,
    CONTRATISTA,
    SOLO_LECTURA,
)

ROLES_GESTION_SST = (
    SUPER_ADMIN,
    ADMIN_EMPRESA,
    RESPONSABLE_SST,
    COORDINADOR_SST,
)

ROLES_OPERACION_SST = (*ROLES_GESTION_SST, TECNICO_SST)
ROLES_ALTA_DIRECCION = (SUPER_ADMIN, ADMIN_EMPRESA, ALTA_DIRECCION, REPRESENTANTE_LEGAL)
ROLES_PARTICIPACION_SST = (COPASST, VIGIA_SST, JEFE_AREA)
ROLES_TRABAJADORES = (EMPLEADO, TRABAJADOR, CONTRATISTA)

ROLES_LECTURA_EJECUTIVA = (
    *ROLES_GESTION_SST,
    TECNICO_SST,
    ALTA_DIRECCION,
    REPRESENTANTE_LEGAL,
    AUDITOR,
    COPASST,
    VIGIA_SST,
    JEFE_AREA,
    TALENTO_HUMANO,
    MEDICO_OCUPACIONAL,
    SOLO_LECTURA,
)

ROLES_PORTAL_EMPLEADO = (
    *ROLES_GESTION_SST,
    TECNICO_SST,
    *ROLES_PARTICIPACION_SST,
    *ROLES_TRABAJADORES,
)


def normalizar_rol(value: object) -> str:
    return str(value or "").strip().upper()
