"""Matriz de roles y permisos normativos SG-SST.

Define qué roles obtienen qué permisos por defecto según Decreto 1072,
Resolución 0312 y Resolución 1843 de 2025.
"""

from app.core.roles import (
    SUPER_ADMIN, ADMIN_EMPRESA, ALTA_DIRECCION, REPRESENTANTE_LEGAL,
    COORDINADOR_SST, RESPONSABLE_SST, TECNICO_SST, JEFE_AREA,
    COPASST, VIGIA_SST, TALENTO_HUMANO, MEDICO_OCUPACIONAL,
    AUDITOR, EMPLEADO, TRABAJADOR, CONTRATISTA, SOLO_LECTURA,
)
from app.core.default_permissions import (
    PERM_REPORTES_EXPORTAR, PERM_REGISTROS_ELIMINAR, PERM_USUARIOS_GESTIONAR,
    PERM_DOCUMENTOS_APROBAR, PERM_EXAMENES_DESCARGAR, PERM_PERMISOS_GESTIONAR,
    PERM_HISTORIA_CLINICA, PERM_CONCEPTO_MEDICO,
)


# Permisos por defecto para cada rol (matriz normativa)
# Fuente: Decreto 1072/2015, Res.0312/2019, Res.1843/2025
ROLES_PERMISOS_DEFAULT: dict[str, list[str]] = {
    SUPER_ADMIN: [
        PERM_REPORTES_EXPORTAR,
        PERM_REGISTROS_ELIMINAR,
        PERM_USUARIOS_GESTIONAR,
        PERM_DOCUMENTOS_APROBAR,
        PERM_EXAMENES_DESCARGAR,
        PERM_PERMISOS_GESTIONAR,
        PERM_HISTORIA_CLINICA,
        PERM_CONCEPTO_MEDICO,
    ],
    ADMIN_EMPRESA: [
        PERM_REPORTES_EXPORTAR,
        PERM_REGISTROS_ELIMINAR,
        PERM_USUARIOS_GESTIONAR,
        PERM_DOCUMENTOS_APROBAR,
        PERM_EXAMENES_DESCARGAR,
        PERM_PERMISOS_GESTIONAR,
    ],
    ALTA_DIRECCION: [
        PERM_REPORTES_EXPORTAR,
        PERM_DOCUMENTOS_APROBAR,
    ],
    REPRESENTANTE_LEGAL: [
        PERM_REPORTES_EXPORTAR,
        PERM_DOCUMENTOS_APROBAR,
    ],
    COORDINADOR_SST: [
        PERM_REPORTES_EXPORTAR,
        PERM_REGISTROS_ELIMINAR,
        PERM_DOCUMENTOS_APROBAR,
        PERM_EXAMENES_DESCARGAR,
    ],
    RESPONSABLE_SST: [
        PERM_REPORTES_EXPORTAR,
        PERM_REGISTROS_ELIMINAR,
        PERM_DOCUMENTOS_APROBAR,
        PERM_EXAMENES_DESCARGAR,
    ],
    TECNICO_SST: [
        PERM_REPORTES_EXPORTAR,
        PERM_EXAMENES_DESCARGAR,
    ],
    JEFE_AREA: [
        PERM_REPORTES_EXPORTAR,
    ],
    COPASST: [
        PERM_REPORTES_EXPORTAR,
    ],
    VIGIA_SST: [],
    TALENTO_HUMANO: [
        PERM_EXAMENES_DESCARGAR,
    ],
    MEDICO_OCUPACIONAL: [
        PERM_EXAMENES_DESCARGAR,
        PERM_HISTORIA_CLINICA,
        PERM_CONCEPTO_MEDICO,
    ],
    AUDITOR: [
        PERM_REPORTES_EXPORTAR,
    ],
    EMPLEADO: [],
    TRABAJADOR: [],
    CONTRATISTA: [],
    SOLO_LECTURA: [],
}


def get_permisos_for_role(rol: str) -> list[str]:
    return ROLES_PERMISOS_DEFAULT.get(rol.upper(), [])
